addons:
  postgresql: "9.4"
language: c
before_install: |
  curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
  sudo apt-get -q update
install: |
  sudo apt-get install crystal
cache: apt
before_script:
  - psql -c 'create database crystal;' -U postgres
env:
  - DATABASE_URL=postgres://postgres@localhost/crystal
script:
  - crystal spec | tee /dev/tty | grep "0 failures, 0 errors" -q
notifications:
  email: false
sudo: true
